### ISSUE TITLE
LUA unlocker

### ISSUE THREAD

**Issue by NiccoJS** [CuteOne/BadRotations-Classic#1]
Do i need an advanced lua unlocker for this?
if yes, which do you recommended?

**Comment by CuteOne** [comment]
This is beta at best, there is a better option available on the BR Discord - discord.gg/tStXqfy

**Comment by NiccoJS** [comment]
didn't found any lua unlockers or better option on the discord server

**Comment by haoqilai2009** [comment]
I entreat your help,Please give me the unlocks that can be used in the classic

**Comment by haoqilai2009** [comment]
> 充其量是beta版，BR Discord上有更好的选择-discord.gg/tStXqfy

Is there any new channel to join in the Discord?

**Comment by MotoAcidic** [comment]
they moved to slack

**Comment by CuteOne** [comment]
https://join.slack.com/t/badrotations/shared_invite/enQtODQ2NjkzNDEzOTA0LWQzY2ZjZTBlYzkwNDc4ZGExMzkzZGVkMmNiZWViMGUzNGQxNmVhMTRhNjIzMDQzYjUzNzAyYTdlZTFlZjA2YTg
