### ISSUE TITLE
wow Classic error

### ISSUE THREAD

**Issue by Pgmlwns** [CuteOne/BadRotations-Classic#2]
Message: ...dOns\BadRotations-Classic\System\Loader\cBuilder.lua:82: attempt to index field '?' (a nil value)
Time: Tue Oct  8 04:17:07 2019
Count: 318
Stack: ...dOns\BadRotations-Classic\System\Loader\cBuilder.lua:82: attempt to index field '?' (a nil value)
...dOns\BadRotations-Classic\System\Loader\cBuilder.lua:82: in function `new'
...nterface\AddOns\BadRotations-Classic\System\Core.lua:205: in function <...nterface\AddOns\BadRotations-Classic\System\Core.lua:108>

Locals: self = <table> {
 new = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cBuilder.lua:68
 loadProfiles = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cBuilder.lua:2
}
spec = "DRUID"
specName = "DRUID"
loadStart = 42304842.470500
self = <table> {
 gcd = 1.500000
 timeToMax = 0
 racial = <table> {
 }
 buff = <table> {
 }
 class = "DRUID"
 enemies = <table> {
 }
 getConsumables = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:321
 gcdMax = 1.500000
 primaryStat = "Agility"
 level = 0
 getPrimaryStat = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:298
 baseUpdate = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:90
 getRacial = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:265
 castRacial = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:270
 getCharacterInfo = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:131
 traits = <table> {
 }
 essence = <table> {
 }
 createBaseOptions = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:287
 pet = <table> {
 }
 queue = <table> {
 }
 moving = false
 baseGetEquip = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:237
 startRotation = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:211
 dynLastUpdate = 0
 getRotation = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:200
 startMeleeAttack = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:183
 glyph = <table> {
 }
 inCombat = false
 opener = <table> {
 }
 getInCombat = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:190
 race = "NightElf"
 getToggleModes = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:161
 baseUpdateOOC = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:148
 flask = <table> {
 }
 getGlobalCooldown = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cCharacter.lua:170
 petId = 0
 spell = <table> {
 }
 debuff = <table> {
 }
 cd = <table> {
 }
 ignoreCombat = false
 rotation = <table> {
 }
 mode = <table> {
 }
 currentPet = "None"
 augmentRune = <table> {
 }
 artifact = <table> {
 }
 charges = <table> {
 }
 dynTargetTimer = 0.500000
 talent = <table> {
 }
 rechargeFull = <table> {
 }
 recharge = <table> {
 }
 equiped = <table> {
 }
 units = <table> {
 }
 profile = "DRUID"
 pandemic = <table> {
 }
 health = 100
 faction = "Alliance"
 potion = <table> {
 }
 selectedRotation = 1
 perk = <table> {
 }
 instance = "none"
}
player = "player"
brLoaded = true
(*temporary) = nil
(*temporary) = 1
(*temporary) = "DRUID"
(*temporary) = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cBuilder.lua:6
(*temporary) = <function> defined @Interface\AddOns\BadRotations-Classic\System\Loader\cBuilder.lua:11
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by CuteOne** [comment]
I recommend DMWC which can be found in BR's discord chat, no futher development is planned on this.
